import './translations.js';

_translationsHash.flags["eng"] = "img/flag_en.png";

_translationsHash.titles["eng"] = "English";

_translationsHash.hash["eng"] = {
	"Да": "Yes",
	"Нет": "No",
	"Карта" : "Map",
	"Создать" : "Create",
	"Создать карту" : "Create map",
	"Сохранить" : "Save",
	"Сохранить как" : "Save as",
	"Сохранить карту как" : "Save map as",
	"Сохранить карту" : "Save map",
	"Экспорт" : "Export",
	"Ссылки" : "Links",

    "Карта пожаров": "Fires map",
    "Поиск снимков": "Search Imagery",
    "Платформа Геомиксер": "GeoMixer Web-GIS",
    "http://fires.ru": "http://fires-map.com",
    "https://search.kosmosnimki.ru": "https://search.kosmosnimki.ru/index_eng.html",

    "Данные": "Datasets",
    "Сервисы": "Services",
    "Поделиться": "Share",
    "Открыть слой": "Open layer",
    "Создать слой": "Create layer",
    "Растровый": "Raster",
    "Векторный": "Vector",
    "Создать группу": "Create group",
    "Базовые слои": "Base layers",
    "Подключить WMS": "Add WMS",
    "Подключить WFS": "Add WFS",
    "Объекты": "User objects",
    "Результаты поиска": "Search results",
    "Буфер": "Buffer",
    "Создание буферных зон": "Buffer zones",
    "Ручная привязка растров": "Manual rasters shift",
    "Поиск слоев на карте": "Search layers on map",
    "Краудсорсинг данных": "Crowdsourcing",
    "Пакетный геокодинг": "Batch geocode",
    "Маршруты": "Directions",
    "Кадастр Росреестра": "Cadastre data of Rosreestr",
    "Выбрать кадастровый объект": "Select Cadastre item",
    "Викимапиа": "Wikimapia",
    "Каталог СКАНЭКС": "Search imagery",
    "Космоснимки-пожары": "Kosmosnimki-fires",
    "GIBS NASA": "MODIS Images (NASA)",
    "Руководство пользователя": "Documentation",
    "Руководство": "User guide",
    "GeoMixer API": "GeoMixer API",
    "Использование плагинов": "Plugins usage",
	"копия": "копия",

	"Открыть" : "Open",
	"Слой" : "Layer",
	"Создать векторный слой" : "Create vector layer",
	"Создать растровый слой" : "Create raster layer",
    "Создать мультислой" : "Create multilayer",
	"Вид" : "View",
	"Дерево слоев" : "Layers tree",
	"Объекты на карте" : "Objects on map",
	"Координатная сетка" : "Coordinate grid",
	"Индексная сетка" : "Index grid",
	"Панель оверлеев" : "Overlays panel",
	"Загрузить объекты" : "Upload objects",
	"Загрузить фотографии" : "Upload photos",
	"Загрузить данные" : "Load data",
		"WFS сервер" : "WFS server",
		"WMS сервер" : "WMS server",
		"Кадастровые данные" : "Cadastre data",
	"Ссылка на карту" : "Link to the map",
	"Код для вставки" : "Embed code",
	"Печать" : "Print",
	"Привязать изображение" : "Bind image",
	"Сообщить об ошибке на карте" : "Report a map error",
	"Справка" : "Help",
	"Использование" : "Usage",
	"О проекте" : "About/Contacts",
	"$$phrase$$_1" : "Choose parameter defaultMapID in config.js file",
	"У вас нет прав на просмотр данной карты" : "Sorry, you don’t have permission to view this map",
	"Access error" : "Sorry, you don’t have permission to view this map",
	"Map not found" : "Sorry, this map not found",
	"Unable to locate EXIF content" : "Unable to locate EXIF content",
	"Развернуть карту" : "Unfold map",
	"Свернуть карту" : "Fold map",
	"Точки на изображении:" : "Points on image:",
	"Точки на карте:" : "Points on map:",
	"Координаты" : "Coordinates",
	"Нарисовать" : "Draw",
	"Восстановить" : "Restore",
	"Прозрачность" : "Transparency",
	"Видимость" : "Visibility",
	"Привязка изображения" : "Image binding",
	"$$phrase$$_2" : "Point [value0] is outside the limits of image",
	"$$phrase$$_3" : "Point [value0] is not specified on a map",
	"Соответствие точек" : "Point correspondence",
	"$$phrase$$_4" : "Points 1 and 2 coincide at the image",
	"$$phrase$$_5" : "Points 1 and 3 coincide at the image",
	"$$phrase$$_6" : "Points 2 and 3 coincide at the image",
	"$$phrase$$_7" : "Points 1 and 2 coincide at the map",
	"$$phrase$$_8" : "Points 1 and 3 coincide at the map ",
	"$$phrase$$_9" : "Points 2 and 3 coincide at the map ",
	"$$phrase$$_10" : "Points lie on a straight line at the image ",
	"Создать экскурсию" : "Create guide",
	"Чтобы пользоваться этим сайтом, установите Flash Player" : "To use this web site, please, install Flash Player",
	"из Интернет" : "from Internet",
	"или с локального диска " : "or from local disc",
	"для Internet Explorer" : "for Internet Explorer",
	" или " : " or ",
	"для Firefox" : "for Firefox",
	"Скачать shp-файл" : "Download shp-file",
	"shp-файл" : "shp-file",
	"gpx-файл" : "gpx-file",
	"Скачать фрагмент растра" : "Download fragment of raster",
	"Очистить" : "Delete",
	"точка" : "point",
	"линия" : "line",
	"прямоугольник" : "rectangle",
	"многоугольник" : "polygon",
	"Скачать" : "Download",
	"Введите имя файла для скачивания" : "Enter file name to download",
	"Выберите область рамкой на карте" : "Select region using frame",
	"Вырезать фрагмент растра" : "Cut fragment of raster",
	"К прямоугольнику не подходит ни одного растрового слоя" : "No one raster layer fit the rectangle",
	"Загруженный shp-файл пуст" : "The uploaded shp-file is empty",
	"Ошибка скачивания" : "Download error",
	"Обновить" : "Update",
	"Домашняя директория" : "Project directory",
	"Имя папки" : "Folder name",
	"Имя" : "Name",
	"Тип" : "Type",
	"Размер" : "Size",
	"Дата" : "Date",
    "Дата создания": "Дата создания",
	"Снять выделение" : "Clear selection",
	"Скопировать" : "Copy",
	"Удалить" : "Delete",
	"Извлечь" : "Extract",
	"Упаковать" : "Add to archive",
	"Загрузить" : "Download",
    "Параметр" : "Parameter",
    "Значение" : "Value",
	"VALUE" : "VALUE",
	"WHERE" : "WHERE",
	"Колонки" : "Columns",
	"Операторы" : "Operators",
	"Функции" : "Functions",
    "Метаданные": "Metadata",
    "Редактировать колонки": "Edit columns",
	"URL сервера" : "Server URL",
	"Формат изображения" : "Image format",
	"Введите имя gml-файла для скачивания:" : "Enter gml-file name to download:",
	"точки" : "points",
	"линии" : "lines",
	"полигоны" : "polygons",
	"(ссылка)" : "(link)",
	"Сохранить состояние карты" : "Save map state",
	"Ссылка на текущее состояние карты" : "Link to the map",
	"Добавить стиль" : "Add style",
	"Атрибут >" : "Attribute >",
	"Значение >" : "Value >",
	"Операция >" : "Operation >",
	"Накладываемое изображение" : "Ground overlay",
	"Цвет" : "Color",
	"Авторизуйтесь для редактирования фильтров" : "Authorize to edit filters",
	"Имя фильтра" : "Filter name",
	"Переместить фильтр вверх" : "Move filter up",
	"Переместить фильтр вниз" : "Move filter down",
	"Удалить фильтр" : "Delete filter",
	"Размер шрифта" : "Typesize",
	"Смещение" : "Shift",
	"Смещение по x" : "X shift",
	"Смещение по y" : "Y shift",
	"Имя атрибута" : "Attribute name",
	"Граница обрезки" : "Clip region",
	"Граница" : "Outline",
	"Толщина линии" : "Line thickness",
	"Заливка" : "Fill",
    "Заливка цветом": "Color fill",
    "Заливка штриховкой": "Pattern fill",
    "Заливка рисунком": "Image fill",
    "Ширина паттерна": "Pattern width",
    "Ширина отступа": "Indent width",
    "URL рисунка": "Image URL",
	"Маркер URL" : "Icon URL ",
	"URL изображения" : "Image URL",
    "Изображение" : "Image",
	"Размер точек" : "Point size",
	"Редактировать стили" : "Edit styles",
	"Авторизуйтесь для редактирования настроек слоя" : " Authorize to edit layer properties",
	"Недостаточно прав для редактирования настроек слоя" : "You have not enough permission to edit layer properties ",
	"Недостаточно прав для редактирования объектов слоя" : "You have not enough permission to edit layer objects ",
	"ID" : "ID",
	"Описание" : "Description",
	"Файл" : "File",
	"Таблица" : "Table",
	"Каталог с тайлами" : "Tile catalogue",
    "Каталог растров" : "Raster catalogue",
    "Данные с датой": "Split through time",
    "Источник": "Source",
    "Дополнительно": "Advanced options",
    "Шаблон названий объектов": "Objects title template",
	"Y (широта)" : "Y (latitude)",
	"X (долгота)" : "X (longitude)",
	"Каталог" : "Catalogue",
	"Изменить" : "Change",
	"Вид вложенных элементов" : "Form of attached elements",
	"Использовать KosmosnimkiAPI" : "Load Kosmosnimki base layers",
	"Использовать OpenStreetMap" : "Use OpenStreetMap",
	"Язык по умолчанию" : "Default language",
    "Единицы длины": "Distance unit",
    "Единицы площади": "Square unit",
	"Формат координат": "Coordinates format",
    "units.auto": "auto",
    "units.m": "m",
    "units.km": "km",
    "units.nm": "nmi",
    "units.m2": "m<sup>2</sup>",
    "units.ha": "ha",
    "units.km2": "km<sup>2</sup>",
	"coords.dd" : "dd.dddd",
	"coords.dms" : "dd°mm′ss″",
	"Генерализация" : "Generalization",
	"gereralization.on": "on",
	"gereralization.off": "off",
	"gereralization.disable": "use layers settings",
	"Количество информационных окошек" : "Max popup count",
    "layerOrder.title": "Layers order",
    "layerOrder.native": "Native",
    "layerOrder.vectorOnTop": "Vector on top",
	"Разрешить поиск в векторных слоях" : "Allow search vector layers",
	"Начальная позиция" : "Start position",
	"Широта" : "Latitude",
	"Долгота" : "Longitude",
	"placeholder degrees": "dd.dddd",
	"placeholder zoom": "1-21",
	"placeholder minZoom": "1",
	"placeholder maxZoom": "21",
	"Зум" : "Zoom",
	"Ссылка (permalink)" : "Permalink",
	"Разрешить скачивание" : "Allow to download",
	"Векторных слоев" : "Vector layers",
	"Растровых слоев" : "Raster layers",
	"Масштабирование в миникарте" : "Minimap zoom delta",
	"Показывать всплывающие подсказки" : "Show tooltips",
	"Свойства" : "Properties",
	"Создать копию слоя" : "Create layer copy",
	"Стили" : "Styles",
	"Изображение на карте" : "Ground overlay",
	"Слой [value0]" : "Layer [value0]",
	"Стили слоя [value0]" : "Styles of layer [value0]",
	"Мультислой [value0]" : "Multilayer [value0]",
	"Группа [value0]" : "Group [value0]",
	"Карта [value0]" : "Map [value0]",
	"Редактировать стиль" : "Edit style",
	"Редактирование стилей объекта" : "Object styles editing",
	"Стили слоя" : "Layer styles",
	"Навигация по карте и инструменты" : "Map navigation and tools",
	"Список слоев" : "List of layers",
	"Стиль векторного слоя" : "Vector layer style",
	"Управление содержанием карты" : "Map content management",
	"Пользовательские инструменты" : "Users tools",
	"$$help$$_1" : "Hold mouse left button – move map with cursor. To zoom in or out use mouse wheel (or map zoom slider to zoom to the cursor position). In order to move map center to specified coordinates – enter coordinates in search line.",
	"$$help$$_2" : "Layer tree is represented in the left panel. To change map center according to layer extent – click its title in the list. If this option was activated by map administrator, you can download vector layers and cut and download raster layers fragments.",
	"$$help$$_3" : "To edit vector layer style click icon near layer name.",
	"$$help$$_4" : "Map is a collection of layers, which is displayed using layer tree. It is necessary to authorize to be able to edit the collection of layers (create groups, change display order etc.) and save changes. For more information see ",
	" - Руководство пользователя" : " – User guide",
	"$$help$$_5" : "User tools serve the purpose of creation of objects on map, which can be saved via «save link to the map», and, at the same time, simple analytic functions fulfillment.",
	"В режиме маркеров: " : "Creating markers: ",
	"$$help$$_6" : "single click – add marker. Double click on marker – delete. Click on marker – open pop-up window (balloon), click on balloon – add text.",
	"В режиме линейка/измерения расстояния, полигон/измерение площади: " : "Drawing lines/distance measurement, polygon/area measurement: ",
	"$$help$$_7" : "single click – add vertex. Double click – complete figure. Click on line – add vertex. Double click on vertex – delete.",
	"$$help$$_8" : "Click on object in list of «objects on map» to move map center to it. You can download object in shp/tab/kml format.",
	"$$about$$_1" : "this web application for interactive geodata view and access to basic data sources in the Internet, such as: ",
	"$$about$$_2" : " Using GeoMixer you can publish own geodata in intranet or in the Internet, put them over basic data coverages and give access to them for however large number of users, changing access permissions.",
	"$$about$$_3" : "GeoMixer also includes API component, which enables integrating the created projects into other web sites and applications and carry out program control over interactive map functional.",
	" - Общее описание" : " – General manual",
	" - Руководство разработчика" : " – Developer’s gudie",
	"Получить API-ключ" : "Get API-key",
	"Введите API-ключ" : "Enter API-key",
	"$$serviceHelp$$_1" : "Allows to upload small shp/tab/kml file on the fly in the form of user objects. After uploading user can edit geometry of objects and download objects in the same format kit.",
	"$$serviceHelp$$_2" : "Link saves current map state, and also user objects and texts.",
	"$$serviceHelp$$_3" : "Print current map fragment.",
	"Редактировать" : "Edit",
    "Удалить объект?": "Delete object?",
    "Удалить отмеченные объекты?": "Delete selected objects?",
	"Длина" : "Length",
	"Площадь" : "Area",
	"Добавить подгруппу" : "Create group",
	"Введите имя группы" : "New group creation",
	"Имя группы" : "Group name",
	"Включая вложенные слои" : "Including attached layers",
	"Удаление группы [value0]" : "Delete group [value0]",
	"Сохранено" : "Saved",
	"Прозрачность выбранного слоя/группы/карты" : "Transparency of the selected layer/group/map",
	"$$updateInfo$$_1" : "To display new layer it is necessary to save and reload map",
	"Любой" : "Any",
	"Владелец" : "Owner",
	"Последнее изменение": "Last modification",
	"Вы действительно хотите удалить этот слой?" : "Do you really want to delete the selected layer?",
	"Ошибка!" : "Error!",
	"Ошибка" : "Error",
	"Выберите колонку" : "Select column",
	"Список карт" : "Maps list",
	"Показать" : "Show",
	"загрузка..." : "loading...",
	"удаление..." : "deleting...",
	"Вы действительно хотите удалить эту карту?" : " Do you really want to delete the selected map?",
    "maplist.hint": "You can drag layers and folders from here to current map",
	"Слоя нет в базе" : "Layer is not in base",
	"ScanEx Web Geomixer - просмотр карты" : "ScanEx Web Geomixer – map view",
	"Изменить параметры поиска" : "Change search parameters",
	"$$search$$_1" : "Search vector layers and address base",
	"$$search$$_2" : "Search address base",
	"Поиск не дал результатов" : "There are no search results",
	"Регистрация" : "Registration",
	"Восстановление пароля" : "Restore password",
	"Вход" : "Login",
	"Выход" : "Logout",
	"Логин" : "User name",
	"Пароль" : "Password",
	"пароль" : "password",
    "Псевдоним": "Nickname",
    "Полное имя": "Full name",
	"Пожалуйста, авторизуйтесь" : "Please, authorize",
    "адрес электронной почты": "enter your e-mail",
	"Ошибка сервера" : "Server error",
	"Папка" : "Folder",
	" и " : " and ",
	"Название" : "Title",
	"Рейтинг" : "Rating",
	"Автор" : "Author",
	"Тематика" : "Theme",
	"Развлекательная" : "Fun",
	"Спортивная" : "Sport",
	"Историческая" : "History",
	"Экологическая" : "Ecology",
	"Любая" : "All",
	"Создать новую тему" : "Create topic",
	"Начало периода" : "Since",
	"Окончание периода" : "Till",
	"Накладываемые тайлы" : "Ground tiles",
	"Отображать с зума" : "Show with zoom",
	"По" : "to",
	"Фильтр" : "Filter",
	"Подпись" : "Label",
	"Балун" : "Balloon",
	"По умолчанию" : "Default",
	"Показывать при клике": "Show on click",
	"Показывать при наведении": "Show on mouse over",
	"Символика" : "Shown style",
    "Библиотека стилей": "Style library",
    "Настройка стилей": "Style settings",
	"скопировать": "copy style",
	"применить везде": "apply to all",
	"Применить": "Apply",
    "Кластеризация" : "Clustering",
	"Минимальный" : "Mininmal",
	"Максимальный" : "Maximal",
	"Мин. зум" : "Min. zoom",
	"Макс. зум" : "Max. zoom",
	"Пешеходная" : "Footpath",
	"Велосипедная" : "Bicycle",
	"Автомобильная" : "Automobile",
	"Места" : "Places",
	"Маршрут" : "Route",
	"Редактировать экскурсию" : "Edit excursion",
	"Добавьте маршрут" : "Add route",
	"Выберете темы на пути следования" : "Choose places throughout the journey",
	"$$phrase$$_11" : "Add route by clicking \"Line\" tool on toolbar",
	"$$phrase$$_12" : "There are no corresponding objects on the map",
	"Выбор маршрута" : "Routes choice",
	"Выбор мест" : "Places choice",
	"$$phrase$$_13" : "You haven't places om map. You can add place in View-Forum tab",
	"Обсуждения" : "Forum",
	"Экскурсии" : "Excursions",
	"$$phrase$$_14" : "Unable to delete default map",
	"$$phrase$$_15" : "Unable to delete current map",
	"Назад" : "Back",
	"Вперед" : "Forward",
	"$$phrase$$_16" : "There is no album with given image ID",
	"Редактировать альбом" : "Edit album",
	"Оценить" : "Vote",
	"Поставьте маркер" : "Add marker",
	"на карту и переместите его в нужное место." : "to map and move it to choosen place.",
	"Недостаточно прав для совершения операции" : "Insufficient rights to perform operation",
	"Новая папка" : "New folder",
	"Выбрать" : "Choose",
	"Добавить" : "Add",
	"$$serviceHelp$$_4" : "Embedding the map: the user can embed a map window into their site by copying and pasting an HTML snippet. An API key for the site's domain is required.",
	"Масштаб" : "Scale",
	"Угол поворота" : "Angle",
	"Диаграммы" : "Charts",
	"График по времени" : "Time chart",
	"Круговая" : "Pie chart",
	"Маска атрибутов" : "Attributes mask",
	"Закладки" : "Bookmarks",
	"Добавить закладку" : "Add bookmark",
	"Имя закладки" : "Bookmark name",
	"Дерево" : "Tree view",
	"Поиск слоев" : "Layers search",
	"Пример выражения": "[Field1]\n[Field2]\nsimple text",
	"Шкала прозрачности" : "Transparency bar",
	"Цвет заливки" : "Fill color",
	"Цвет обводки" : "Outline color",
	"Цвет шрифта" : "Font color",
	"Легенда" : "Legend",
	"Событие загрузки карты" : "Событие загрузки карты",
	"Мин" : "Min",
	"Макс" : "Max",
	"График" : "График",
	"Гистограмма" : "Гистограмма",
	"Столбчатая" : "Столбчатая",
	"Временная" : "Временная",
	"Копировать стиль" : "Copy style",
	"Применить стиль" : "Apply style",
	"Не выбран стиль" : "There is no copied style",
	"Невозможно применить стиль к другому типу геометрии" : "Can't apply style to different geometry type",
	"Общие" : "Common",
	"Доступ" : "Policy",
	"Окно карты" : "View",
	"Загрузка" : "Onload",
	"Копирайт" : "Copyright",
	"Инструменты" : "Tools",
	"Загрузить KML" : "Load KML",
	"URL файла" : "File URL",
    "Поиск" : "Search",
    "Подложки": "Base Layers",
    "Доступные подложки": "Available base layers",
    "Подложки карты": "Base layers on map",
    "Выберите слои для поиска по атрибутам": "Select layers for attributes search",
	"Включить синхронизацию слоев": "Enable sync layers",
	"Выключить синхронизацию слоев": "Disable sync layers",

	"Редактирование прав доступа карты [value0]" : "Map [value0] access editor",
	"Редактирование прав доступа слоя [value0]" : "Layer [value0] access editor",
	"Редактирование прав доступа слоев карты [value0]" : "Map [value0] layers access editor",
	"Состав группы [value0]" : "Users of group [value0]",
	"Роль" : "Role",
	"Добавить пользователя" : "Add user",
	"Права доступа" : "Access permissions",
	"Права доступа к слоям" : "Layers access permissions",
	"Пользователи без прав доступа:" : "Users wihout access:",
	"Пользователи с правами доступа:" : "Users with access:",
	"Выберите нового владельца" : "Select new owner",
	"Сменить владельца" : "Change owner",

	"Объекты RuMap" : "RuMap objects",
	"Объекты пользователей" : "User objects",

	"Контакты" : "Contacts",
	"Фотографии" : "Photo",
	"Момент съемки" : "Image date",
	"Видео" : "Video",
	"Сообщения" : "Messages",
	"Ссылка на место" : "Ссылка на место",
	"Ссылка на экскурсию" : "Ссылка на экскурсию",
	"Ссылка на событие" : "Ссылка на событие",
	"Создать новое событие" : "Создать новое событие",
	"События" : "События",
	"Календарь" : "Календарь",
	"Новости" : "Новости",
	"Мероприятия" : "Мероприятия",
	"Отмена" : "Отмена",
	"Пропустить" : "Skip",
	"Время" : "Время",
	"Альбом OpenPhotoVR" : "Фотоальбом",
	"Встраиваемый код" : "Embed video",

	"Объекты экологического риска" : "Объекты экологического риска",
		"Санкционированные свалки" : "Санкционированные свалки",
		"Несанкционированные свалки" : "Несанкционированные свалки",
		"Полигоны отходов" : "Полигоны отходов",
		"Предприятия переработки отходов" : "Предприятия переработки отходов",
		"Факельные установки, ТЭЦ, трубы" : "Факельные установки, ТЭЦ, трубы",
		"Закрытые свалки" : "Закрытые свалки",
		"Пункты приема отходов" : "Пункты приема отходов",
		"Оползни" : "Оползни",
		"Карстовые явления" : "Карстовые явления",
		"Суффозионные явления" : "Суффозионные явления",

	"Государство и общество" : "Государство и общество",
		"Радио" : "Радио",
		"Правительственные учреждения" : "Правительственные учреждения",
		"Оптики" : "Оптики",
		"Охранные агенства" : "Охранные агенства",
		"Травмпункты" : "Травмпункты",
		"Таможня" : "Таможня",
		"Ветеринарные клиники" : "Ветеринарные клиники",
		"ЗАГС" : "ЗАГС",
		"Больницы" : "Больницы",
		"Аптеки" : "Аптеки",
		"Поликлиники" : "Поликлиники",
		"Колледжи" : "Колледжи",
		"Университеты" : "Университеты",
		"ОВИР" : "ОВИР",
		"Посольства" : "Посольства",
		"Почтовые отделения" : "Почтовые отделения",
		"Суды" : "Суды",
		"Банки" : "Банки",
		"Родильные дома" : "Родильные дома",
		"Дома престарелых" : "Дома престарелых",
		"Детские сады" : "Детские сады",
		"Школы" : "Школы",
		"Инспекции" : "Инспекции",
		"Адвокаты" : "Адвокаты",
		"МЧС" : "МЧС",
		"Муниципальные учреждения" : "Муниципальные учреждения",
		"Администрация" : "Администрация",

	"Культура и отдых" : "Культура и отдых",
		"Боулинг" : "Боулинг",
		"Аквапарки" : "Аквапарки",
		"Парки развлечений" : "Парки развлечений",
		"Библиотеки" : "Библиотеки",
		"Памятники" : "Памятники",
		"Лагери отдыха" : "Лагери отдыха",
		"Кинотеатры" : "Кинотеатры",
		"Цирки" : "Цирки",
		"Галереи" : "Галереи",
		"Отели" : "Отели",
		"Мотели" : "Мотели",
		"Музеи" : "Музеи",
		"Концертные залы" : "Концертные залы",
		"Ночные клубы" : "Ночные клубы",
		"Театры" : "Театры",
		"Санатории" : "Санатории",
		"Зоопарки" : "Зоопарки",

	"Общественное питание" : "Общественное питание",
		"Кафе" : "Кафе",
		"Фастфуды" : "Фастфуды",
		"Рестораны" : "Рестораны",
		"Кафе-мороженое" : "Кафе-мороженое",
		"Столовые" : "Столовые",

	"Природные достопримечательности" : "Природные достопримечательности",
		"Ботанический сад" : "Ботанические сады",
		"Пещеры" : "Пещеры",
		"Водопады" : "Водопады",
		"Парки" : "Парки",
		"Источники" : "Источники",
		"Заповедники" : "Заповедники",
		"Прочие архитектурные и природные достопримечательности" : "Архитектурные достопримечательности",

	"Религия" : "Религия",
		"Культовые сооружения" : "Культовые сооружения",
		"Мечети" : "Мечети",
		"Монастыри" : "Монастыри",
		"Церкви других христианских конфессий" : "Церкви других христианских конфессий",
		"Православные церкви" : "Православные церкви",
		"Синагоги" : "Синагоги",

	"Спорт" : "Спорт",
		"Стадионы" : "Стадионы",
		"Теннисные корты" : "Теннисные корты",
		"Катки" : "Катки",
		"Ипподромы" : "Ипподромы",
		"Фитнес" : "Фитнес",
		"Бассейны" : "Бассейны",
		"Прокат спортинвентаря" : "Прокат спортинвентаря",

	"Торговля и услуги" : "Торговля и услуги",
		"Солярии" : "Солярии",
		"Интернет-кафе" : "Интернет-кафе",
		"Рынки" : "Рынки",
		"Стоматологические клиники" : "Стоматологические клиники",
		"Магазины одежды" : "Магазины одежды",
		"Парикмахерские" : "Парикмахерские",
		"Бани" : "Бани",
		"Магазины обуви" : "Магазины обуви",
		"Магазины" : "Магазины",
		"Ателье" : "Ателье",
		"Такси" : "Такси",
		"Туризм" : "Туризм",

	"Транспорт и услуги" : "Транспорт и услуги",
		"Аэропорты" : "Аэропорты",
		"Автосервисы" : "Автосервисы",
		"Автовокзалы" : "Автовокзалы",
		"ДПС" : "ДПС",
		"ГИБДД" : "ГИБДД",
		"Шиномонтаж" : "Шиномонтаж",
		"Парковки бесплатные" : "Парковки бесплатные",
		"Парковки платные" : "Парковки платные",
		"АЗС" : "АЗС",
		"Автомойки" : "Автомойки",

	"Экстренные службы" : "Экстренные службы",
		"Пожарные/спасатели" : "Пожарные/спасатели",
		"Милиция" : "Милиция",
		"Скорая помощь" : "Скорая помощь",

	"Другие темы" : "Другие темы",
		"Разное" : "Разное",

	"Изменение пароля" : "Password change",
	"Новый пароль" : "New password",
	"Старый пароль" : "Old password",
	"Подтвердите пароль" : "Confirm password",
	"Контур" : "Border",
	"$$phrase$$_17" : "Add border by clicking \"Polygon\" tool on toolbar",
	"Выбор контура" : "Border select",
	"Таблица атрибутов слоя [value0]" : "[value0] attributes table",
	"Показать параметры поиска" : "Show search params",
	"Скрыть параметры поиска" : "Hide search params",
	"Скрыть" : "Hide",
	"Искать внутри полигона" : "Search inside polygon",
	"Искать по пересечению с объектом" : "Search by geometry",
	"SQL-условие WHERE" : "WHERE SQL expression",
	"Показывать колонки" : "Show columns",
	"Скрыть колонки" : "Hide columns",
	"Найти" : "Search",
	"Нет полей" : "Empty fields",
	"Нет данных" : "Empty data",
	"Таблица атрибутов" : "Attributes table",
	"Разрешить поиск" : "Allow search",
	"Произвольный" : "Any",
	"День" : "Day",
	"Неделя" : "Week",
	"Месяц" : "Month",
	"Год" : "Year",
	"Ежегодно" : "Every year",
	"Облачность" : "Clouds",
	"Период" : "Period",
	"Спутниковые покрытия" : "Satellite cover",
	"Редактировать объект слоя [value0]" : "Edit layer [value0] object",
	"Создать объект слоя [value0]" : "Add layer [value0] object",
	"Геометрия" : "Geometry",
	"Найти объекты" : "Find objects",
	"Добавить объекты" : "Add objects",
	"Обновить объекты" : "Update objects",
	"Копировать объекты" : "Copy objects",
	"Объекты скопированы" : "Objects are copied",
	"Объекты добавлены" : "Объекты добавлены",
	"Вставить объекты" : "Paste objects",
	"Вставить объекты не удалось" : "Paste objects failed",
	"Выберите правым кликом слой в левой панели и нажмите \"Вставить объекты\"": "Right-click on layer name and select \"Paste objects\"",
	"Изменить колонки" : "Update columns",
	"Обновить колонку" : "Update column",
	"Очистить поиск" : "Clean search",
    "Скачать shp": "Download shp",
    "Скачать gpx": "Download gpx",
    "Скачать csv": "Download csv",
    "Скачать geojson": "Download geojson",
    "Рассчитать площадь": "Total square",
	"Создать столбец" : "Create column",
	"Мультислой" : "Multilayer",
	"В дереве слоев остались несохраненные изменения!" : "There are unsaved changes on layers tree!",
	"файл версии отсутствует" : "version file doesn't exists",
	"оверлеи отсутствуют" : "no overlays present",
	"Хост" : "Host",
	"Дополнительные карты" : "Additional maps",
	"Добавить карту" : "Add map",
	"Добавить в таймлайн" : "Add to timeLine",
	"Удалить из таймлайна" : "Remove from timeline",
	"Невозможно загрузить карту [value0] с домена [value1]" : "Unable to load map [value0] from domain [value1]",
	"Показывать" : "Show",
	"Принудительно обновить тайлы" : "Forced retiling",
	"Обводка" : "Outline",
	"Карта имеет более новую версию. Сохранить?" : "The map has a newer version. Save anyway?",
	"Кодировка": "Encoding",
	"helpPostfix": "_eng.html",
	"Показывать чекбокс видимости": "Visibility checkbox",
	"Разворачивать автоматически": "Expand automatically",
	"Другая": "Another",
	"Временнóй слой": "Multitemporal layer",
	"Колонка даты": "Date column",
	"Минимальный период": "Min. period (days)",
	"Максимальный период": "Max. period (days)",
    "Отсутствует временной атрибут": "Missing attribute with type 'Date'",
    "Период 1 день": "Period 1 day",
    "Показывать на карте данные за": "Show data on map within",
    "1 день": "single day",
    "произвольный период" : "arbitrary period",
	"По границе экрана": "Screen border",
	"По центру экрана": "Screen center",
	"Пересечение": "Intersection",
	"Пролистывать слои": "Scroll layers",
	"Следующий слой": "Next layer",
	"Предыдущий слой": "Previous layer",
    "Геометрия не сохранена. Эта возможность будет реализована в будущих версиях Геомиксера.": "Geometry is not saved. This feature will be implemented in future Geomixer versions",
    "WMS доступ": "WMS/WFS access",
    "ссылка": "link",
    "Слой '[value0]' уже есть в карте": "Layer '[value0]' already exists in this map",
    "Группа '[value0]' уже есть в карте": "Group '[value0]' already exists in this map",
    "Плагины": "Plugins",
    "Вручную": "Manually",
    "Добавить атрибут": "Add attribute",
    "Проекция": "Projection",
    "Широта/Долгота (EPSG:4326)": "Lat/Lon (EPSG:4326)",
    "Меркатор (EPSG:3395)": "Mercator (EPSG:3395)",
    "Из файла": "From file",
    "Мультиполигон": "Multipolygon",
    "Мультилиния": "Multipolyline",
    "Мультиточка": "Multipoint",
    "Администрирование": "Administration",
    "Системные настройки": "System settings",
    "Управление группами": "User group management",
    "Управление группами пользователей": "User group management",
    "Добавить снимки": "Add rasters",
    "Существующие слои": "Existing layers",
    "Слои из карты": "Layers from map",
    "Слои из КР": "Layers from RC",
    "Новый слой": "New layer",
    "С экрана": "Select on map",
    "Добавлен растр": "Raster is added",
    "Добавлены растры": "Rasters are added",
    "Выбранный объект не имеет растра": "Selected object has no raster",
    "Этот растр уже был выбран": "This raster is already selected",
    "Каталог Растров": "Raster catalog",
    "Растр": "Raster",
    "Добавить выбранные растры": "Add selected rasters",
    "EditObject.menuTitle" : "Add object",
    "FileBrowser.ExceedLimitMessage" : "File size exceeds 500 Mb. Use GeoMixerFileBrowser tool to upload large files.",
    "FileBrowser.DropInfo" : "Drop files here",
    "EditObject.drawingMenuTitle" : "Add object to active layer",
    "Поставить маркер": "Add marker",
    "Центрировать": "Set center",
    "Пароль изменён": "Password has been changed",
	"портретная": "portrait view",
	"альбомная": "layout view",
	"gmx_geometry": "gmx_geometry"
};
